site_name: "Layan's Digital Garden"
site_url: "https://layanalnasser.github.io/My-Garden/"

theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.instant
    - search.suggest
    - search.highlight
    - content.code.copy
  palette:
    - scheme: default
      primary: red
      accent: deep orange
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    - scheme: slate
      primary: red
      accent: deep orange
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
  icon:
    logo: material/robot-outline
  font:
    text: Inter
    code: Fira Code

nav:
  - Home: index.md

  - Academics:
      - Overview: academics/index.md
      - Notes & Learning: academics/notes.md
      - Resources: academics/resources.md

  - Career Development:
      - About Me: career/about.md
      - Resume / CV: career/cv.md
      - Projects: career/projects.md
      - Activities & Workshops: career/activities.md

  - Links: links.md

markdown_extensions:
  - admonition
  - toc:
      permalink: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.superfences
  - pymdownx.inlinehilite
  - pymdownx.details
  - pymdownx.highlight
  - pymdownx.magiclink
  - footnotes
  - def_list
  - tables
  - attr_list

plugins:
  - search

extra_css:
  - styles/extra.css
